// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetURL provides a mock function with given fields: ctx, id
func (_m *Repository) GetURL(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreURL provides a mock function with given fields: ctx, code, url, expireIn
func (_m *Repository) StoreURL(ctx context.Context, code string, url string, expireIn int) error {
	ret := _m.Called(ctx, code, url, expireIn)

	if len(ret) == 0 {
		panic("no return value specified for StoreURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, code, url, expireIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreURLIfAbsent provides a mock function with given fields: ctx, code, url, expireIn
func (_m *Repository) StoreURLIfAbsent(ctx context.Context, code string, url string, expireIn int) (bool, error) {
	ret := _m.Called(ctx, code, url, expireIn)

	if len(ret) == 0 {
		panic("no return value specified for StoreURLIfAbsent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (bool, error)); ok {
		return rf(ctx, code, url, expireIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) bool); ok {
		r0 = rf(ctx, code, url, expireIn)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, code, url, expireIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
